// Label overrides per locale. Only keys that differ from the US default are listed.
// Values are the primary display label for that key in this locale.

export const LOCALES = {
  'en-US': { name: 'English (US)', overrides: {} },

  'en-GB': {
    name: 'English (UK)',
    overrides: {
      Digit2:          '"',
      Digit3:          '£',
      Backquote:       '¬',
      BracketLeft:     '[',
      BracketRight:    ']',
      Hash:            '#',
      Backslash:       '#',
      IntlHash:        '#',
      IntlBackslash:   '\\',
    },
  },

  'cs-CZ': {
    name: 'Čeština (QWERTZ)',
    overrides: {
      KeyY:          'Z',
      KeyZ:          'Y',
      Digit1:        '+',
      Digit2:        'ě',
      Digit3:        'š',
      Digit4:        'č',
      Digit5:        'ř',
      Digit6:        'ž',
      Digit7:        'ý',
      Digit8:        'á',
      Digit9:        'í',
      Digit0:        'é',
      Minus:         '=',
      Equal:         '´',
      BracketLeft:   'ú',
      BracketRight:  ')',
      Backslash:     '¨',
      Semicolon:     'ů',
      Quote:         '§',
      IntlHash:      '¨',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'da-DK': {
    name: 'Dansk',
    overrides: {
      Backquote:     '½',
      Minus:         '+',
      Equal:         '´',
      BracketLeft:   'Å',
      BracketRight:  '¨',
      Backslash:     "'",
      Semicolon:     'Æ',
      Quote:         'Ø',
      IntlHash:      "'",
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'de-DE': {
    name: 'Deutsch (QWERTZ)',
    overrides: {
      KeyY:          'Z',
      KeyZ:          'Y',
      Digit2:        '2',
      Digit3:        '3',
      Digit6:        '6',
      Digit7:        '7',
      Digit8:        '8',
      BracketLeft:   'Ü',
      BracketRight:  '+',
      Backslash:     '#',
      Semicolon:     'Ö',
      Quote:         'Ä',
      IntlHash:      '#',
      IntlBackslash: '<',
      Minus:         'ß',
      Equal:         '´',
      Backquote:     '^',
      Slash:         '-',
      Period:        '.',
      Comma:         ',',
    },
  },

  'de-CH': {
    name: 'Deutsch (Schweiz, QWERTZ)',
    overrides: {
      KeyY:          'Z',
      KeyZ:          'Y',
      Backquote:     '§',
      Minus:         "'",
      Equal:         '^',
      BracketLeft:   'ü',
      BracketRight:  '¨',
      Backslash:     '$',
      Semicolon:     'ö',
      Quote:         'ä',
      IntlHash:      '$',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'es-ES': {
    name: 'Español (España)',
    overrides: {
      Backquote:     'º',
      Minus:         "'",
      Equal:         '¡',
      BracketLeft:   '`',
      BracketRight:  '+',
      Backslash:     'ç',
      Semicolon:     'Ñ',
      Quote:         '´',
      IntlHash:      'ç',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'es-419': {
    name: 'Español (Latinoamérica)',
    overrides: {
      Backquote:     '|',
      Minus:         "'",
      Equal:         '¡',
      BracketLeft:   '`',
      BracketRight:  '+',
      Backslash:     '}',
      Semicolon:     'Ñ',
      Quote:         '´',
      IntlHash:      '\\',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'fr-FR': {
    name: 'Français (AZERTY)',
    overrides: {
      KeyQ:          'A',
      KeyA:          'Q',
      KeyW:          'Z',
      KeyZ:          'W',
      KeyM:          ',',
      Comma:         ';',
      Period:        ':',
      Slash:         '!',
      Digit1:        '&',
      Digit2:        'É',
      Digit3:        '"',
      Digit4:        "'",
      Digit5:        '(',
      Digit6:        '-',
      Digit7:        'È',
      Digit8:        '_',
      Digit9:        'Ç',
      Digit0:        'À',
      Minus:         ')',
      Equal:         '=',
      Backquote:     '²',
      BracketLeft:   '^',
      BracketRight:  '$',
      Backslash:     '*',
      Semicolon:     'M',
      Quote:         'Ù',
      IntlBackslash: '<',
    },
  },

  'fr-BE': {
    name: 'Français (Belgique, AZERTY)',
    overrides: {
      KeyQ:          'A',
      KeyA:          'Q',
      KeyW:          'Z',
      KeyZ:          'W',
      KeyM:          ',',
      Comma:         ';',
      Period:        ':',
      Slash:         '=',
      Digit1:        '&',
      Digit2:        'é',
      Digit3:        '"',
      Digit4:        "'",
      Digit5:        '(',
      Digit6:        '§',
      Digit7:        'è',
      Digit8:        '!',
      Digit9:        'ç',
      Digit0:        'à',
      Minus:         ')',
      Equal:         '-',
      Backquote:     '²',
      BracketLeft:   '^',
      BracketRight:  '$',
      Backslash:     'µ',
      Semicolon:     'M',
      Quote:         'ù',
      IntlBackslash: '<',
    },
  },

  'nl-BE': {
    name: 'Nederlands (België, AZERTY)',
    overrides: {
      KeyQ:          'A',
      KeyA:          'Q',
      KeyW:          'Z',
      KeyZ:          'W',
      KeyM:          ',',
      Comma:         ';',
      Period:        ':',
      Slash:         '=',
      Digit1:        '&',
      Digit2:        'é',
      Digit3:        '"',
      Digit4:        "'",
      Digit5:        '(',
      Digit6:        '§',
      Digit7:        'è',
      Digit8:        '!',
      Digit9:        'ç',
      Digit0:        'à',
      Minus:         ')',
      Equal:         '-',
      Backquote:     '²',
      BracketLeft:   '^',
      BracketRight:  '$',
      Backslash:     'µ',
      Semicolon:     'M',
      Quote:         'ù',
      IntlBackslash: '<',
    },
  },

  'it-IT': {
    name: 'Italiano',
    overrides: {
      Backquote:     '\\',
      Minus:         "'",
      Equal:         'ì',
      BracketLeft:   'è',
      BracketRight:  '+',
      Backslash:     'ù',
      Semicolon:     'ò',
      Quote:         'à',
      IntlHash:      'ù',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'hu-HU': {
    name: 'Magyar (QWERTZ)',
    overrides: {
      KeyY:          'Z',
      KeyZ:          'Y',
      Digit0:        'Ö',
      Minus:         'Ü',
      Equal:         'Ó',
      BracketLeft:   'Ő',
      BracketRight:  'Ú',
      Backslash:     'Ű',
      Semicolon:     'É',
      Quote:         'Á',
      IntlHash:      'Ű',
      IntlBackslash: 'Í',
      Slash:         '-',
    },
  },

  'nl-NL': {
    name: 'Nederlands',
    overrides: {
      Backquote:     '@',
      IntlBackslash: '<',
    },
  },

  'nb-NO': {
    name: 'Norsk',
    overrides: {
      Backquote:     '|',
      Minus:         '+',
      Equal:         '\\',
      BracketLeft:   'Å',
      BracketRight:  '¨',
      Backslash:     '@',
      Semicolon:     'Ø',
      Quote:         'Æ',
      IntlHash:      '@',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'pl-PL': {
    name: 'Polski',
    overrides: {
      IntlBackslash: '<',
    },
  },

  'pt-BR': {
    name: 'Português (Brasil)',
    overrides: {
      Backquote:     "'",
      BracketLeft:   '´',
      BracketRight:  '[',
      Backslash:     ']',
      Semicolon:     'Ç',
      Quote:         '~',
      IntlHash:      ']',
      IntlBackslash: '\\',
      Slash:         ';',
    },
  },

  'pt-PT': {
    name: 'Português (Portugal)',
    overrides: {
      Backquote:     '\\',
      Minus:         "'",
      Equal:         '«',
      BracketLeft:   '+',
      BracketRight:  '´',
      Backslash:     '~',
      Semicolon:     'Ç',
      Quote:         'º',
      IntlHash:      '~',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'ro-RO': {
    name: 'Română',
    overrides: {
      BracketLeft:   'ș',
      BracketRight:  'î',
      Quote:         'ă',
      IntlHash:      'â',
      IntlBackslash: '<',
    },
  },

  'sk-SK': {
    name: 'Slovenčina (QWERTZ)',
    overrides: {
      KeyY:          'Z',
      KeyZ:          'Y',
      Digit1:        '+',
      Digit2:        'ľ',
      Digit3:        'š',
      Digit4:        'č',
      Digit5:        'ť',
      Digit6:        'ž',
      Digit7:        'ý',
      Digit8:        'á',
      Digit9:        'í',
      Digit0:        'é',
      Minus:         '=',
      Equal:         '´',
      BracketLeft:   'ú',
      BracketRight:  'ä',
      Backslash:     '¨',
      Semicolon:     'ô',
      Quote:         '§',
      IntlHash:      '¨',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'fi-FI': {
    name: 'Suomi',
    overrides: {
      Backquote:     '§',
      Minus:         '+',
      Equal:         '´',
      BracketLeft:   'Å',
      BracketRight:  '¨',
      Backslash:     "'",
      Semicolon:     'Ö',
      Quote:         'Ä',
      IntlHash:      "'",
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'sv-SE': {
    name: 'Svenska',
    overrides: {
      Backquote:     '§',
      Minus:         '+',
      Equal:         '´',
      BracketLeft:   'Å',
      BracketRight:  '¨',
      Backslash:     "'",
      Semicolon:     'Ö',
      Quote:         'Ä',
      IntlHash:      "'",
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'tr-TR': {
    name: 'Türkçe (Q)',
    overrides: {
      Backquote:     '"',
      Minus:         '*',
      Equal:         '-',
      BracketLeft:   'Ğ',
      BracketRight:  'Ü',
      Backslash:     ',',
      Semicolon:     'Ş',
      Quote:         'İ',
      Comma:         'Ö',
      Period:        'Ç',
      Slash:         '.',
      IntlHash:      ',',
      IntlBackslash: '<',
    },
  },

  'el-GR': {
    name: 'Ελληνικά',
    overrides: {
      KeyQ: ';',
      KeyW: 'ς',
      KeyE: 'ε',
      KeyR: 'ρ',
      KeyT: 'τ',
      KeyY: 'υ',
      KeyU: 'θ',
      KeyI: 'ι',
      KeyO: 'ο',
      KeyP: 'π',
      KeyA: 'α',
      KeyS: 'σ',
      KeyD: 'δ',
      KeyF: 'φ',
      KeyG: 'γ',
      KeyH: 'η',
      KeyJ: 'ξ',
      KeyK: 'κ',
      KeyL: 'λ',
      KeyZ: 'ζ',
      KeyX: 'χ',
      KeyC: 'ψ',
      KeyV: 'ω',
      KeyB: 'β',
      KeyN: 'ν',
      KeyM: 'μ',
      Semicolon:     '΄',
      IntlBackslash: '<',
    },
  },

  'ru-RU': {
    name: 'Русский',
    overrides: {
      Backquote:    'ё',
      KeyQ: 'й', KeyW: 'ц', KeyE: 'у', KeyR: 'к', KeyT: 'е',
      KeyY: 'н', KeyU: 'г', KeyI: 'ш', KeyO: 'щ', KeyP: 'з',
      BracketLeft: 'х', BracketRight: 'ъ',
      KeyA: 'ф', KeyS: 'ы', KeyD: 'в', KeyF: 'а', KeyG: 'п',
      KeyH: 'р', KeyJ: 'о', KeyK: 'л', KeyL: 'д',
      Semicolon: 'ж', Quote: 'э',
      KeyZ: 'я', KeyX: 'ч', KeyC: 'с', KeyV: 'м',
      KeyB: 'и', KeyN: 'т', KeyM: 'ь',
      Comma: 'б', Period: 'ю', Slash: '.',
    },
  },

  'uk-UA': {
    name: 'Українська',
    overrides: {
      Backquote:    'ґ',
      KeyQ: 'й', KeyW: 'ц', KeyE: 'у', KeyR: 'к', KeyT: 'е',
      KeyY: 'н', KeyU: 'г', KeyI: 'ш', KeyO: 'щ', KeyP: 'з',
      BracketLeft: 'х', BracketRight: 'ї',
      KeyA: 'ф', KeyS: 'і', KeyD: 'в', KeyF: 'а', KeyG: 'п',
      KeyH: 'р', KeyJ: 'о', KeyK: 'л', KeyL: 'д',
      Semicolon: 'ж', Quote: 'є',
      KeyZ: 'я', KeyX: 'ч', KeyC: 'с', KeyV: 'м',
      KeyB: 'и', KeyN: 'т', KeyM: 'ь',
      Comma: 'б', Period: 'ю', Slash: '.',
    },
  },

  'ko-KR': {
    name: '한국어',
    overrides: {
      KeyQ: 'ㅂ', KeyW: 'ㅈ', KeyE: 'ㄷ', KeyR: 'ㄱ', KeyT: 'ㅅ',
      KeyY: 'ㅛ', KeyU: 'ㅕ', KeyI: 'ㅑ', KeyO: 'ㅐ', KeyP: 'ㅔ',
      KeyA: 'ㅁ', KeyS: 'ㄴ', KeyD: 'ㅇ', KeyF: 'ㄹ', KeyG: 'ㅎ',
      KeyH: 'ㅗ', KeyJ: 'ㅓ', KeyK: 'ㅏ', KeyL: 'ㅣ',
      KeyZ: 'ㅋ', KeyX: 'ㅌ', KeyC: 'ㅊ', KeyV: 'ㅍ',
      KeyB: 'ㅠ', KeyN: 'ㅜ', KeyM: 'ㅡ',
    },
  },

  'zh-CN': {
    name: '简体中文',
    overrides: {},
  },

  'ja-JP': {
    name: '日本語',
    overrides: {
      Equal:        '^',
      BracketLeft:  '@',
      BracketRight: '[',
      Backslash:    '¥',
      IntlHash:     ']',
      Quote:        ':',
    },
  },

  'id-ID': {
    name: 'Bahasa Indonesia',
    overrides: {},
  },

  'vi-VN': {
    name: 'Tiếng Việt',
    overrides: {},
  },

  'bg-BG': {
    name: 'Български',
    overrides: {
      Backquote:    'ч',
      KeyQ: 'я', KeyW: 'в', KeyE: 'е', KeyR: 'р', KeyT: 'т',
      KeyY: 'ъ', KeyU: 'у', KeyI: 'и', KeyO: 'о', KeyP: 'п',
      BracketLeft: 'ш', BracketRight: 'щ', Backslash: 'ю',
      KeyA: 'а', KeyS: 'с', KeyD: 'д', KeyF: 'ф', KeyG: 'г',
      KeyH: 'х', KeyJ: 'й', KeyK: 'к', KeyL: 'л',
      KeyZ: 'з', KeyX: 'ь', KeyC: 'ц', KeyV: 'ж',
      KeyB: 'б', KeyN: 'н', KeyM: 'м',
      IntlHash: 'ю', IntlBackslash: '<',
    },
  },

  'sr-RS': {
    name: 'Српски',
    overrides: {
      KeyQ: 'љ', KeyW: 'њ', KeyE: 'е', KeyR: 'р', KeyT: 'т',
      KeyY: 'з', KeyU: 'у', KeyI: 'и', KeyO: 'о', KeyP: 'п',
      BracketLeft: 'ш', BracketRight: 'ђ',
      KeyA: 'а', KeyS: 'с', KeyD: 'д', KeyF: 'ф', KeyG: 'г',
      KeyH: 'х', KeyJ: 'ј', KeyK: 'к', KeyL: 'л',
      Semicolon: 'ч', Quote: 'ћ',
      KeyZ: 'ж', KeyX: 'џ', KeyC: 'ц', KeyV: 'в',
      KeyB: 'б', KeyN: 'н', KeyM: 'м',
      IntlBackslash: '<',
    },
  },

  'hr-HR': {
    name: 'Hrvatski (QWERTZ)',
    overrides: {
      KeyY:          'Z',
      KeyZ:          'Y',
      BracketLeft:   'Š',
      BracketRight:  'Đ',
      Backslash:     'Ž',
      Semicolon:     'Č',
      Quote:         'Ć',
      IntlHash:      'Ž',
      IntlBackslash: '<',
    },
  },
};

export const LOCALE_IDS = Object.keys(LOCALES);

// Locales whose physical keyboards use the ISO 105-key standard (extra IntlHash
// and IntlBackslash keys, L-shaped Enter). Everything else defaults to ANSI 104.
const ISO_LOCALE_SET = new Set([
  'bg-BG',
  'cs-CZ', 'da-DK', 'de-DE', 'de-CH',
  'el-GR', 'es-ES',
  'fi-FI', 'fr-FR', 'fr-BE',
  'hr-HR', 'hu-HU', 'it-IT',
  'ja-JP',
  'nb-NO', 'nl-NL', 'nl-BE',
  'pl-PL', 'pt-PT', 'ro-RO',
  'sk-SK', 'sr-RS', 'sv-SE',
  'tr-TR',
  'en-GB',
]);

export function localeUsesISO(localeId) {
  return ISO_LOCALE_SET.has(localeId);
}

// Returns the locale-specific label for a key, or null if no override exists.
export function getLocaleLabel(keyId, localeId) {
  return LOCALES[localeId]?.overrides?.[keyId] ?? null;
}

// Returns display label: locale override → layout default label → keyId fallback.
export function resolveLabel(keyId, keyDef, localeId) {
  return getLocaleLabel(keyId, localeId) ?? keyDef?.label ?? keyId;
}
