// Label overrides per locale. Only keys that differ from the US default are listed.
// Values are the primary display label for that key in this locale.

export const LOCALES = {
  'en-US': { name: 'English (US)', overrides: {} },

  'en-GB': {
    name: 'English (UK)',
    overrides: {
      Digit2:          '"',
      Digit3:          '£',
      Backquote:       '¬',
      BracketLeft:     '[',
      BracketRight:    ']',
      Hash:            '#',     // same position, different label convention
      Backslash:       '#',     // ANSI position — on ISO this is IntlHash
      IntlHash:        '#',
      IntlBackslash:   '\\',
    },
  },

  'de-DE': {
    name: 'Deutsch (QWERTZ)',
    overrides: {
      KeyY:          'Z',
      KeyZ:          'Y',
      Digit2:        '2',
      Digit3:        '3',
      Digit6:        '6',
      Digit7:        '7',
      Digit8:        '8',
      BracketLeft:   'Ü',
      BracketRight:  '+',
      Backslash:     '#',
      Semicolon:     'Ö',
      Quote:         'Ä',
      IntlHash:      '#',
      IntlBackslash: '<',
      Minus:         'ß',
      Equal:         '´',
      Backquote:     '^',
      Slash:         '-',
      Period:        '.',
      Comma:         ',',
    },
  },

  'fr-FR': {
    name: 'Français (AZERTY)',
    overrides: {
      KeyQ:          'A',
      KeyA:          'Q',
      KeyW:          'Z',
      KeyZ:          'W',
      KeyM:          ',',
      Comma:         ';',
      Period:        ':',
      Slash:         '!',
      Digit1:        '&',
      Digit2:        'É',
      Digit3:        '"',
      Digit4:        "'",
      Digit5:        '(',
      Digit6:        '-',
      Digit7:        'È',
      Digit8:        '_',
      Digit9:        'Ç',
      Digit0:        'À',
      Minus:         ')',
      Equal:         '=',
      Backquote:     '²',
      BracketLeft:   '^',
      BracketRight:  '$',
      Backslash:     '*',
      Semicolon:     'M',
      Quote:         'Ù',
      IntlBackslash: '<',
    },
  },

  'sv-SE': {
    name: 'Svenska',
    overrides: {
      Backquote:     '§',
      Minus:         '+',
      Equal:         '´',
      BracketLeft:   'Å',
      BracketRight:  '¨',
      Backslash:     "'",
      Semicolon:     'Ö',
      Quote:         'Ä',
      IntlHash:      "'",
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'fi-FI': {
    name: 'Suomi',
    overrides: {
      Backquote:     '§',
      Minus:         '+',
      Equal:         '´',
      BracketLeft:   'Å',
      BracketRight:  '¨',
      Backslash:     "'",
      Semicolon:     'Ö',
      Quote:         'Ä',
      IntlHash:      "'",
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'nb-NO': {
    name: 'Norsk',
    overrides: {
      Backquote:     '|',
      Minus:         '+',
      Equal:         '\\',
      BracketLeft:   'Å',
      BracketRight:  '¨',
      Backslash:     '@',
      Semicolon:     'Ø',
      Quote:         'Æ',
      IntlHash:      '@',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'da-DK': {
    name: 'Dansk',
    overrides: {
      Backquote:     '½',
      Minus:         '+',
      Equal:         '´',
      BracketLeft:   'Å',
      BracketRight:  '¨',
      Backslash:     "'",
      Semicolon:     'Æ',
      Quote:         'Ø',
      IntlHash:      "'",
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'es-ES': {
    name: 'Español (España)',
    overrides: {
      Backquote:     'º',
      Minus:         "'",
      Equal:         '¡',
      BracketLeft:   '`',
      BracketRight:  '+',
      Backslash:     'ç',
      Semicolon:     'Ñ',
      Quote:         '´',
      IntlHash:      'ç',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'es-419': {
    name: 'Español (Latinoamérica)',
    overrides: {
      Backquote:     '|',
      Minus:         "'",
      Equal:         '¡',
      BracketLeft:   '`',
      BracketRight:  '+',
      Backslash:     '}',
      Semicolon:     'Ñ',
      Quote:         '´',
      IntlHash:      '\\',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'pt-BR': {
    name: 'Português (Brasil)',
    overrides: {
      Backquote:     "'",
      BracketLeft:   '´',
      BracketRight:  '[',
      Backslash:     ']',
      Semicolon:     'Ç',
      Quote:         '~',
      IntlHash:      ']',
      IntlBackslash: '\\',
      Slash:         ';',
    },
  },

  'pt-PT': {
    name: 'Português (Portugal)',
    overrides: {
      Backquote:     '\\',
      Minus:         "'",
      Equal:         '«',
      BracketLeft:   '+',
      BracketRight:  '´',
      Backslash:     '~',
      Semicolon:     'Ç',
      Quote:         'º',
      IntlHash:      '~',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'it-IT': {
    name: 'Italiano',
    overrides: {
      Backquote:     '\\',
      Minus:         "'",
      Equal:         'ì',
      BracketLeft:   'è',
      BracketRight:  '+',
      Backslash:     'ù',
      Semicolon:     'ò',
      Quote:         'à',
      IntlHash:      'ù',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'de-CH': {
    name: 'Deutsch (Schweiz, QWERTZ)',
    overrides: {
      KeyY:          'Z',
      KeyZ:          'Y',
      Backquote:     '§',
      Minus:         "'",
      Equal:         '^',
      BracketLeft:   'ü',
      BracketRight:  '¨',
      Backslash:     '$',
      Semicolon:     'ö',
      Quote:         'ä',
      IntlHash:      '$',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'fr-BE': {
    name: 'Français (Belgique, AZERTY)',
    overrides: {
      KeyQ:          'A',
      KeyA:          'Q',
      KeyW:          'Z',
      KeyZ:          'W',
      KeyM:          ',',
      Comma:         ';',
      Period:        ':',
      Slash:         '=',
      Digit1:        '&',
      Digit2:        'é',
      Digit3:        '"',
      Digit4:        "'",
      Digit5:        '(',
      Digit6:        '§',
      Digit7:        'è',
      Digit8:        '!',
      Digit9:        'ç',
      Digit0:        'à',
      Minus:         ')',
      Equal:         '-',
      Backquote:     '²',
      BracketLeft:   '^',
      BracketRight:  '$',
      Backslash:     'µ',
      Semicolon:     'M',
      Quote:         'ù',
      IntlBackslash: '<',
    },
  },

  'nl-NL': {
    name: 'Nederlands',
    overrides: {
      Backquote:     '@',
      IntlBackslash: '<',
    },
  },

  'pl-PL': {
    name: 'Polski',
    overrides: {
      IntlBackslash: '<',
    },
  },

  'cs-CZ': {
    name: 'Čeština (QWERTZ)',
    overrides: {
      KeyY:          'Z',
      KeyZ:          'Y',
      Digit1:        '+',
      Digit2:        'ě',
      Digit3:        'š',
      Digit4:        'č',
      Digit5:        'ř',
      Digit6:        'ž',
      Digit7:        'ý',
      Digit8:        'á',
      Digit9:        'í',
      Digit0:        'é',
      Minus:         '=',
      Equal:         '´',
      BracketLeft:   'ú',
      BracketRight:  ')',
      Backslash:     '¨',
      Semicolon:     'ů',
      Quote:         '§',
      IntlHash:      '¨',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'sk-SK': {
    name: 'Slovenčina (QWERTZ)',
    overrides: {
      KeyY:          'Z',
      KeyZ:          'Y',
      Digit1:        '+',
      Digit2:        'ľ',
      Digit3:        'š',
      Digit4:        'č',
      Digit5:        'ť',
      Digit6:        'ž',
      Digit7:        'ý',
      Digit8:        'á',
      Digit9:        'í',
      Digit0:        'é',
      Minus:         '=',
      Equal:         '´',
      BracketLeft:   'ú',
      BracketRight:  'ä',
      Backslash:     '¨',
      Semicolon:     'ô',
      Quote:         '§',
      IntlHash:      '¨',
      IntlBackslash: '<',
      Slash:         '-',
    },
  },

  'hu-HU': {
    name: 'Magyar (QWERTZ)',
    overrides: {
      KeyY:          'Z',
      KeyZ:          'Y',
      Digit0:        'Ö',
      Minus:         'Ü',
      Equal:         'Ó',
      BracketLeft:   'Ő',
      BracketRight:  'Ú',
      Backslash:     'Ű',
      Semicolon:     'É',
      Quote:         'Á',
      IntlHash:      'Ű',
      IntlBackslash: 'Í',
      Slash:         '-',
    },
  },

  'ro-RO': {
    name: 'Română',
    overrides: {
      BracketLeft:   'ș',
      BracketRight:  'î',
      Quote:         'ă',
      IntlHash:      'â',
      IntlBackslash: '<',
    },
  },

  'tr-TR': {
    name: 'Türkçe (Q)',
    overrides: {
      Backquote:     '"',
      Minus:         '*',
      Equal:         '-',
      BracketLeft:   'Ğ',
      BracketRight:  'Ü',
      Backslash:     ',',
      Semicolon:     'Ş',
      Quote:         'İ',
      Comma:         'Ö',
      Period:        'Ç',
      Slash:         '.',
      IntlHash:      ',',
      IntlBackslash: '<',
    },
  },

  'el-GR': {
    name: 'Ελληνικά',
    overrides: {
      KeyQ: ';',
      KeyW: 'ς',
      KeyE: 'ε',
      KeyR: 'ρ',
      KeyT: 'τ',
      KeyY: 'υ',
      KeyU: 'θ',
      KeyI: 'ι',
      KeyO: 'ο',
      KeyP: 'π',
      KeyA: 'α',
      KeyS: 'σ',
      KeyD: 'δ',
      KeyF: 'φ',
      KeyG: 'γ',
      KeyH: 'η',
      KeyJ: 'ξ',
      KeyK: 'κ',
      KeyL: 'λ',
      KeyZ: 'ζ',
      KeyX: 'χ',
      KeyC: 'ψ',
      KeyV: 'ω',
      KeyB: 'β',
      KeyN: 'ν',
      KeyM: 'μ',
      Semicolon:     '΄',
      IntlBackslash: '<',
    },
  },
};

export const LOCALE_IDS = Object.keys(LOCALES);

// Returns the locale-specific label for a key, or null if no override exists.
export function getLocaleLabel(keyId, localeId) {
  return LOCALES[localeId]?.overrides?.[keyId] ?? null;
}

// Returns display label: locale override → layout default label → keyId fallback.
export function resolveLabel(keyId, keyDef, localeId) {
  return getLocaleLabel(keyId, localeId) ?? keyDef?.label ?? keyId;
}
